### ISSUE TITLE
do we need a code of conduct?

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/GaiaSprint#18]
If we do, let's make an issue for it and adopt something (relatively) standard

**Comment by andycasey** [comment]
There’s no reason not to, and there is relatively little effort to adopt one. There is a standard one on GitHub that came as a result of a science hack week, IIRC. If you want, you can assign this to me and I will find a relatively standard one that sensibly respects all.

**Comment by adrn** [comment]
@andycasey Do it!

**Comment by davidwhogg** [comment]
assigned. Put a link to the policy in the paragraph about open science, but don't quote the policy in full on the top page -- too much text! Maybe just a two-sentence summary of it.

**Comment by andycasey** [comment]
After looking around, I have found some boilerplate code of conducts which are recommended for tech/science conferences. The one below is adapted from http://confcodeofconduct.com/ and http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy

The short line I propose to add to the open science paragraph is:

> "The Gaia Sprints organizers are dedicated to providing a harassment-free conference experience for everyone. Participants must follow the code of conduct."

And this will link to a page containing the following code of conduct:

> The Gaia Sprints organizers are dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of conference participants in any form. Sexual language and imagery is not appropriate for any conference venue, including talks, workshops, parties, Twitter and other online media. Participants violating these rules may be sanctioned or expelled from the Gaia Sprint without a refund at the discretion of the conference organizers.
> 
> Harassment includes offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, technology choices, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.
> 
> Participants asked to stop any harassing behavior are expected to comply immediately. If a participant engages in harassing behavior, the organizers may take any action they deem appropriate, including warning the offender or expulsion from the Gaia Sprint with no refund.
> 
> If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact an organizer immediately. Organizers will be happy to help participants contact hotel/venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the Gaia Sprint. We value your attendance.
> 
> We expect participants to follow these rules during the Gaia Sprint and during related social events.

Too strong? Not strong enough? Is the scope appropriate?

One question I have is whether we should prefix the short or long version with something to the effect of "Although no harassment has been reported during the first Gaia Sprint, there are good reasons to establish a code of conduct for future events." ('good reasons' could link to a Google search for "should academic conferences have a code of conduct")

**Comment by davidwhogg** [comment]
I like all of this, and I do want to preface any code with the comment that our community is good, safe, supportive, and so on. Reassign this issue to me

**Comment by andycasey** [comment]
If you need my help including this on the website or linking this together, just re-assign me.

**Comment by davidwhogg** [comment]
done
