### ISSUE TITLE
Who is on the organizing committee for 2017?

### ISSUE THREAD

**Issue by adrn** [davidwhogg/GaiaSprint#19]

**Comment by davidwhogg** [comment]
We could keep it as no change. Any thoughts about who should be added or subtracted? I will ask Spergel if he wants to stay on the OC.

**Comment by davidwhogg** [comment]
I have dropped Spergel and kept everyone else. I will still invite Spergel to stay, but I will explicitly invite him. If anyone wants off, let me know.

Since @wilmatrick will have moved on, I need a HD member to add -- email me if you have suggestions.

**Comment by davidwhogg** [comment]
ps @wilmatrick I have kept you on the OC! I'm just saying we need a local in HD.

**Comment by davidwhogg** [comment]
Spergel said yes; Buder & Coronado are LOC. Closing
