### ISSUE TITLE
Is it possible to move the 2016 NYC Gaia Sprint to a separate page?

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/GaiaSprint#20]
(I have no idea how gh-pages works.)

If it is possible, can you move it there, and make the links to the final slides very prominent?

**Comment by adrn** [comment]
It is possible, but I don't immediately know how to do it. Will have to wait unless someone else has the time...

**Comment by andycasey** [comment]
Yeah I can do this

**Comment by davidwhogg** [comment]
assigned you

**Comment by davidwhogg** [comment]
thanks and I made (and pushed) some tweaks.
