### ISSUE TITLE
add a list of publications to the 2016 NYC page

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/GaiaSprint#31]
On the page http://davidwhogg.github.io/GaiaSprint/2016NYC.html , add, in the "Results" section at the top, after the wrap-up slides paragraph, a bulleted list of papers that have hit the arXiv that thank the sprint.

**Comment by adrn** [comment]
Heres what I've seen so far:

- https://arxiv.org/abs/1612.02440
- https://arxiv.org/abs/1611.04614
- https://arxiv.org/abs/1611.07035
- https://arxiv.org/abs/1610.08563
- https://arxiv.org/abs/1610.07610

Chao has submitted a paper to ApJL but it's not on arxiv.
