### ISSUE TITLE
make "built at GaiaSprint" github / web badge?

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/GaiaSprint#4]
I feel like @andycasey or @adrn might know how to do this...?

Like the badges here https://github.com/davidwhogg/JamesBradley

**Comment by andycasey** [comment]
![sprint](https://img.shields.io/badge/built%20at-%23GaiaSprint-orange.svg)

Colors and styling available through http://shields.io/ under "Your Badge"

**Comment by davidwhogg** [comment]
COOL.  Now should we make it "built at" or should we make it "built for"?

**Comment by davidwhogg** [comment]
ps. Aren't you in Phase II?

**Comment by andycasey** [comment]
"built at" IMHO. I'm procrastarPhasing.

**Comment by davidwhogg** [comment]
Excellent; closing!
