### ISSUE TITLE
send out homework emails

### ISSUE THREAD

**Issue by davidwhogg** [davidwhogg/GaiaSprint#8]
We want various kinds of homework
- problems with DR1 data products -- gotchas
- short introductions to other public data sets
- reading of existing papers on the arXiv and preparation for 5-minute summaries
- interfaces to the data, including by xyz, uvw, and so on
- preparation to make a 2-minute pitch on day 1.

**Comment by adrn** [comment]
- Cool data visualizations of DR1

**Comment by davidwhogg** [comment]
@andycasey @wilmatrick do you two have ideas for things we should be giving as homework?

Also @adrn and everyone: Who should get which homework assignment?

**Comment by andycasey** [comment]
No additional ideas. But **everyone** should be prepared to make a 2 minute pitch on day 1.

**Comment by davidwhogg** [comment]
@wilmatrick can you bring to the Sprint an API or code such that people at the Sprint can have / use actions?

**Comment by wilmatrick** [comment]
Hi David,

Yes, of course. I can prepare a little code snippet for everyone using
Jo's galpy to calculate actions. However, people would need to install
galpy beforehand. That could be some additional homework task for those
interested. Also, it would be good to specify what exactly a pitch is in
the email. I'm for example not 100% sure what this is. With slides or
without?

 Are you planning to have short breakout sessions? I'm thinking of 15min
presentations for those interested about technical stuff, e.g. how to use
galpy, how to cross match surveys with topcat, if people have some code
they are willing to share and introduce (the Binney group has also action
estimation codes on github, I believe) etc.

Sorry That I did not answer earlier. I'm currently traveling and typing
this on my phone...

Cheers,
Wilma

**Comment by davidwhogg** [comment]
Oh good point -- we should give advice on installations...

**Comment by davidwhogg** [comment]
Other ideas:
- [ ] code / api for projecting stellar spectra onto bandpasses (Fouesneau)
- [ ] distance priors as a function of ra, dec
- [ ] metallicity priors / MDF (Kordopatis)

**Comment by davidwhogg** [comment]
- [ ] code / api for querying a good 3-d dust map
- [ ] matches to all spectroscopy and spectroscopic labels
- [ ] matches to all asteroseismology
- [ ] matches to all known exoplanets and binary stars

**Comment by davidwhogg** [comment]
about to send...
